import type { CountrySignalSource } from "./types";

export const chileSignalSources = [
  {
    id: "cl.dmc.wrf",
    name: "DMC Weather / WRF",
    authority: "Dirección Meteorológica de Chile",
    domain: "weather",
    authMode: "user_token",
    cadence: "WRF updates around 08:00 and 20:00 local time",
    priority: "P0",
    canonicalUrl: "https://climatologia.meteochile.gob.cl/",
    description: "Weather observations and regional WRF forecast signals.",
  },
  {
    id: "cl.mtt.observatorio-logistico",
    name: "Observatorio Logístico",
    authority: "Ministerio de Transportes y Telecomunicaciones",
    domain: "logistics",
    authMode: "api_key",
    cadence: "Dataset-dependent; operational resources can update daily",
    priority: "P0",
    canonicalUrl: "https://datos.observatoriologistico.cl/",
    description: "Port, freight, border crossing and logistics signals.",
  },
  {
    id: "cl.bcn.leychile",
    name: "LeyChile",
    authority: "Biblioteca del Congreso Nacional de Chile",
    domain: "regulation",
    authMode: "api_key",
    cadence: "Daily publication flow",
    priority: "P0",
    canonicalUrl: "https://www.bcn.cl/leychile/",
    description: "New, modified and versioned Chilean regulation.",
  },
  {
    id: "cl.dga.hydrometric",
    name: "DGA Alertas Fluviométricas",
    authority: "Dirección General de Aguas",
    domain: "water",
    authMode: "none",
    cadence: "Station readings update every 15 to 60 minutes; about 30 minutes on average",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/DGA/ALERTAS/MapServer/0",
    description: "Official river-flow readings and DGA alert levels from the hydrometeorological network.",
  },
  {
    id: "cl.mop.vialidad.emergencias",
    name: "MOP Emergencias Viales",
    authority: "Dirección de Vialidad, Ministerio de Obras Públicas",
    domain: "logistics",
    authMode: "none",
    cadence: "Updated during active road emergencies, generally around 15:00 local time",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/VIALIDAD/Emergencias_Vialidad/MapServer/0",
    description: "Current road emergencies with route, restriction, transit, severity and operability.",
  },
  {
    id: "cl.mop.vialidad.pasos-fronterizos",
    name: "MOP Pasos Fronterizos",
    authority: "Dirección de Vialidad, Ministerio de Obras Públicas",
    domain: "logistics",
    authMode: "none",
    cadence: "Daily",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/VIALIDAD/Pasos_Fronterizos/MapServer/0",
    description: "Border-crossing transitability, road condition, weather, chain requirements and restrictions.",
  },
  {
    id: "cl.mop.emergencias-infraestructura",
    name: "MOP Emergencias de Infraestructura",
    authority: "Ministerio de Obras Públicas",
    domain: "emergency",
    authMode: "none",
    cadence: "Event-driven through SIEMOP updates",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/EMERGENCIA/EMERGENCIA_MOP/MapServer/0",
    description: "Operational degradation across roads, ports, airports, rural water, waterways, irrigation and public infrastructure.",
  },
  {
    id: "cl.conaf.wildfire-forecast",
    name: "CONAF Pronóstico de Incendios",
    authority: "Corporación Nacional Forestal",
    domain: "emergency",
    authMode: "none",
    cadence: "Forecast maps published Monday, Wednesday and Friday",
    priority: "P0",
    canonicalUrl: "https://www.conaf.cl/incendios/situacion-actual-y-pronostico-de-incendios/",
    description: "Official wildfire forecast context including ignition probability and dead fine fuel moisture.",
  },
  {
    id: "cl.conaf.boton-rojo",
    name: "CONAF Botón Rojo",
    authority: "Corporación Nacional Forestal",
    domain: "emergency",
    authMode: "none",
    cadence: "Daily; public projection up to five days",
    priority: "P0",
    canonicalUrl: "https://www.conaf.cl/incendios/situacion-actual-y-pronostico-de-incendios/",
    description: "Official territorial wildfire risk flag combining ignition probability and wind conditions.",
  },
  {
    id: "cl.conaf.active-fires",
    name: "CONAF Incendios Activos",
    authority: "Corporación Nacional Forestal",
    domain: "emergency",
    authMode: "none",
    cadence: "Public situation information refreshed every 5 minutes",
    priority: "P0",
    canonicalUrl: "https://www.conaf.cl/incendios/situacion-actual-y-pronostico-de-incendios/",
    description: "Official current wildfire situation; machine-readable production contract still requires validation.",
  },
  {
    id: "cl.bcch.bde",
    name: "Banco Central BDE",
    authority: "Banco Central de Chile",
    domain: "economy",
    authMode: "token",
    cadence: "Series-dependent",
    priority: "P1",
    canonicalUrl: "https://si3.bcentral.cl/",
    description: "FX, UF, CPI, rates, trade and macroeconomic context.",
  },
  {
    id: "cl.cne.generacion-bruta",
    name: "CNE Generación Bruta",
    authority: "Comisión Nacional de Energía",
    domain: "energy",
    authMode: "none",
    cadence: "Monthly",
    priority: "P1",
    canonicalUrl: "https://datos.gob.cl/dataset/generacion-bruta",
    description: "Official monthly gross electricity generation by technology and subsystem.",
  },
] as const satisfies readonly CountrySignalSource[];

export function getCountrySignalSource(sourceId: string): CountrySignalSource | undefined {
  return chileSignalSources.find((source) => source.id === sourceId);
}

export function requireCountrySignalSource(sourceId: string): CountrySignalSource {
  const source = getCountrySignalSource(sourceId);
  if (!source) {
    throw new Error(`Country signal source is not registered: ${sourceId}`);
  }
  return source;
}
