import type { CountrySignalSource } from "./types";

export const chileSignalSources = [
  {
    id: "cl.dmc.wrf",
    name: "DMC Weather / WRF",
    authority: "Dirección Meteorológica de Chile",
    domain: "weather",
    authMode: "user_token",
    cadence: "WRF updates around 08:00 and 20:00 local time",
    priority: "P0",
    canonicalUrl: "https://climatologia.meteochile.gob.cl/",
    description: "Weather observations and regional WRF forecast signals.",
  },
  {
    id: "cl.mma.sinca-air-quality",
    name: "SINCA Calidad del Aire en Línea",
    authority: "Ministerio del Medio Ambiente",
    domain: "environment",
    authMode: "none",
    cadence: "Hourly online update",
    priority: "P0",
    canonicalUrl: "https://sinca.mma.gob.cl/index.php/json/listadomapa2k19/",
    description: "Current online air-quality indicators from SINCA stations, preserved as provisional until MMA validation.",
  },
  {
    id: "cl.mtt.observatorio-logistico",
    name: "Observatorio Logístico",
    authority: "Ministerio de Transportes y Telecomunicaciones",
    domain: "logistics",
    authMode: "api_key",
    cadence: "Dataset-dependent; operational resources can update daily",
    priority: "P0",
    canonicalUrl: "https://datos.observatoriologistico.cl/",
    description: "Port, freight, border crossing and logistics signals.",
  },
  {
    id: "cl.bcn.leychile",
    name: "LeyChile",
    authority: "Biblioteca del Congreso Nacional de Chile",
    domain: "regulation",
    authMode: "api_key",
    cadence: "Daily publication flow",
    priority: "P0",
    canonicalUrl: "https://www.bcn.cl/leychile/",
    description: "New, modified and versioned Chilean regulation.",
  },
  {
    id: "cl.dga.hydrometric",
    name: "DGA Alertas Fluviométricas",
    authority: "Dirección General de Aguas",
    domain: "water",
    authMode: "none",
    cadence: "Station readings update every 15 to 60 minutes; about 30 minutes on average",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/DGA/ALERTAS/MapServer/0",
    description: "Official river-flow readings and DGA alert levels from the hydrometeorological network.",
  },
  {
    id: "cl.dga.reservoirs-vipnet",
    name: "DGA VIPNet Embalses",
    authority: "Dirección General de Aguas",
    domain: "water",
    authMode: "none",
    cadence: "Hourly completed-window snapshot",
    priority: "P0",
    canonicalUrl: "https://vipnet.mop.gob.cl/",
    description: "Current reservoir-volume snapshots from the DGA Visualizador Hidrométrico Nacional using VIPNet's official latest-value statistic.",
  },
  {
    id: "cl.dga.scarcity-decrees",
    name: "DGA Decretos de Escasez Hídrica",
    authority: "Dirección General de Aguas",
    domain: "water",
    authMode: "none",
    cadence: "Daily legal-status check",
    priority: "P0",
    canonicalUrl: "https://dga.mop.gob.cl/derechos-de-agua/proteccion-de-las-fuentes/decretos-de-escasez-2/",
    description: "Official scarcity-decree status derived from each DGA-listed decree's explicit decree date and expiration date.",
  },
  {
    id: "cl.mop.vialidad.emergencias",
    name: "MOP Emergencias Viales",
    authority: "Dirección de Vialidad, Ministerio de Obras Públicas",
    domain: "logistics",
    authMode: "none",
    cadence: "Updated during active road emergencies, generally around 15:00 local time",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/VIALIDAD/Emergencias_Vialidad/MapServer/0",
    description: "Current road emergencies with route, restriction, transit, severity and operability.",
  },
  {
    id: "cl.mop.vialidad.pasos-fronterizos",
    name: "MOP Pasos Fronterizos",
    authority: "Dirección de Vialidad, Ministerio de Obras Públicas",
    domain: "logistics",
    authMode: "none",
    cadence: "Daily",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/VIALIDAD/Pasos_Fronterizos/MapServer/0",
    description: "Border-crossing transitability, road condition, weather, chain requirements and restrictions.",
  },
  {
    id: "cl.mop.emergencias-infraestructura",
    name: "MOP Emergencias de Infraestructura",
    authority: "Ministerio de Obras Públicas",
    domain: "emergency",
    authMode: "none",
    cadence: "Event-driven through SIEMOP updates",
    priority: "P0",
    canonicalUrl: "https://rest-sit.mop.gob.cl/arcgis/rest/services/EMERGENCIA/EMERGENCIA_MOP/MapServer/0",
    description: "Operational degradation across roads, ports, airports, rural water, waterways, irrigation and public infrastructure.",
  },
  {
    id: "cl.conaf.wildfire-forecast",
    name: "CONAF Pronóstico de Incendios",
    authority: "Corporación Nacional Forestal",
    domain: "emergency",
    authMode: "none",
    cadence: "Forecast maps published Monday, Wednesday and Friday",
    priority: "P0",
    canonicalUrl: "https://www.conaf.cl/incendios/situacion-actual-y-pronostico-de-incendios/",
    description: "Official wildfire forecast context including ignition probability and dead fine fuel moisture.",
  },
  {
    id: "cl.conaf.boton-rojo",
    name: "CONAF Botón Rojo",
    authority: "Corporación Nacional Forestal",
    domain: "emergency",
    authMode: "none",
    cadence: "Daily; public projection up to five days",
    priority: "P0",
    canonicalUrl: "https://www.conaf.cl/incendios/situacion-actual-y-pronostico-de-incendios/",
    description: "Official territorial wildfire risk flag combining ignition probability and wind conditions.",
  },
  {
    id: "cl.conaf.active-fires",
    name: "CONAF Incendios Activos",
    authority: "Corporación Nacional Forestal",
    domain: "emergency",
    authMode: "none",
    cadence: "Public situation information refreshed every 5 minutes",
    priority: "P0",
    canonicalUrl: "https://www.conaf.cl/incendios/situacion-actual-y-pronostico-de-incendios/",
    description: "Official current wildfire situation queried from the public CONAF Power BI semantic model.",
  },
  {
    id: "cl.cen.cmg-online",
    name: "Coordinador CMg en Línea",
    authority: "Coordinador Eléctrico Nacional",
    domain: "energy",
    authMode: "api_key",
    cadence: "15-minute operational intervals",
    priority: "P0",
    canonicalUrl: "https://sipub.api.coordinador.cl/costos-marginales-online-8b/v4/findAll",
    description: "Online marginal cost for the official representative SEN bars, expressed in USD/MWh.",
  },
  {
    id: "cl.cen.demand-net",
    name: "Coordinador Demanda Neta",
    authority: "Coordinador Eléctrico Nacional",
    domain: "energy",
    authMode: "api_key",
    cadence: "Operational time series",
    priority: "P0",
    canonicalUrl: "https://sipub.api.coordinador.cl/demanda-neta/v4/findByDate",
    description: "Official net demand time series for the National Electric System.",
  },
  {
    id: "cl.cen.generation-real",
    name: "Coordinador Generación Real",
    authority: "Coordinador Eléctrico Nacional",
    domain: "energy",
    authMode: "api_key",
    cadence: "Current-day generation by technology",
    priority: "P0",
    canonicalUrl: "https://sipub.api.coordinador.cl/generacion-real/v3/getDailySum",
    description: "Official current-day real generation summed by technology.",
  },
  {
    id: "cl.cen.transmission-limitations",
    name: "Coordinador Limitaciones de Transmisión",
    authority: "Coordinador Eléctrico Nacional",
    domain: "energy",
    authMode: "api_key",
    cadence: "Operational / event-driven",
    priority: "P0",
    canonicalUrl: "https://sipub.api.coordinador.cl/limitaciones-transmision/v4/findByDate",
    description: "Official transmission limitations for anticipating grid constraints and downstream impacts.",
  },
  {
    id: "cl.cen.reservoirs",
    name: "Coordinador Embalses",
    authority: "Coordinador Eléctrico Nacional",
    domain: "water",
    authMode: "api_key",
    cadence: "Current reservoir level plus weekly history",
    priority: "P1",
    canonicalUrl: "https://sipub.api.coordinador.cl/embalse-real/v3/findLast",
    description: "Current official reservoir levels used by the electricity system.",
  },
  {
    id: "cl.cen.fuel-stock",
    name: "Coordinador Stock de Combustible",
    authority: "Coordinador Eléctrico Nacional",
    domain: "energy",
    authMode: "api_key",
    cadence: "Operational date-range dataset",
    priority: "P1",
    canonicalUrl: "https://sipub.api.coordinador.cl/stock-combustible/v4/findByDate",
    description: "Official fuel stock available for electricity generation.",
  },
  {
    id: "cl.bcch.bde",
    name: "Banco Central BDE",
    authority: "Banco Central de Chile",
    domain: "economy",
    authMode: "token",
    cadence: "Series-dependent",
    priority: "P1",
    canonicalUrl: "https://si3.bcentral.cl/",
    description: "FX, UF, CPI, rates, trade and macroeconomic context.",
  },
  {
    id: "cl.cne.liquid-fuel-prices",
    name: "CNE Precio Combustibles Líquidos",
    authority: "Comisión Nacional de Energía",
    domain: "energy",
    authMode: "token",
    cadence: "Monthly regional series",
    priority: "P0",
    canonicalUrl: "https://api.cne.cl/api/ea/precio/combustibleliquido",
    description: "Official regional liquid-fuel price per liter series from the current CNE API.",
  },
  {
    id: "cl.cne.liquid-fuel-sales",
    name: "CNE Venta Mensual Combustibles Líquidos",
    authority: "Comisión Nacional de Energía",
    domain: "energy",
    authMode: "token",
    cadence: "Monthly regional series",
    priority: "P1",
    canonicalUrl: "https://api.cne.cl/api/ea/venta/combustibleliquido/mensual",
    description: "Official monthly regional liquid-fuel sales volume by fuel and sale type from the current CNE API.",
  },
  {
    id: "cl.cne.generacion-bruta",
    name: "CNE Generación Bruta",
    authority: "Comisión Nacional de Energía",
    domain: "energy",
    authMode: "none",
    cadence: "Monthly",
    priority: "P1",
    canonicalUrl: "https://datos.gob.cl/dataset/generacion-bruta",
    description: "Official monthly gross electricity generation by technology and subsystem.",
  },
] as const satisfies readonly CountrySignalSource[];

export function getCountrySignalSource(sourceId: string): CountrySignalSource | undefined {
  return chileSignalSources.find((source) => source.id === sourceId);
}

export function requireCountrySignalSource(sourceId: string): CountrySignalSource {
  const source = getCountrySignalSource(sourceId);
  if (!source) throw new Error(`Country signal source is not registered: ${sourceId}`);
  return source;
}
